font_family      Libertinus Mono
bold_font        Libertinus Mono Bold
italic_font      Libertinus Mono Italic
bold_italic_font Libertinus Mono Bold Italic
font_size        12.0
window_padding_width 10

background            #1b1b1b
foreground            #e2e2e2
cursor                #e2e2e2
cursor_text_color     #1b1b1b

selection_background  #464646
selection_foreground  #e2e2e2

url_color             #e2e2e2

color0  #2e2e2e
color1  #676767
color2  #767676
color3  #858585
color4  #949494
color5  #a3a3a3
color6  #b2b2b2
color7  #e2e2e2

color8  #464646
color9  #787878
color10 #878787
color11 #969696
color12 #a5a5a5
color13 #b4b4b4
color14 #c3c3c3
color15 #ffffff

enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell no
bell_on_tab no


background_opacity 1.0

